// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412222758_InitialSupabase")]
    partial class InitialSupabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Backend.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SelectedColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SelectedSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvailableColors")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AvailableSizes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("numeric");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableColors = "[\"White\",\"Blue\",\"Light Blue\"]",
                            AvailableSizes = "[\"S\",\"M\",\"L\",\"XL\",\"XXL\"]",
                            Category = "Men",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Shirt",
                            Name = "Classic Oxford Shirt",
                            Price = 79.99m,
                            SKU = "MEN-SHT-001",
                            StockQuantity = 45,
                            SubCategory = "Shirts"
                        },
                        new
                        {
                            Id = 2,
                            AvailableColors = "[\"Dark Wash\",\"Black\"]",
                            AvailableSizes = "[\"30\",\"32\",\"34\",\"36\"]",
                            Category = "Men",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1542272604-787c3835535d?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Jeans",
                            Name = "Slim Dark Jeans",
                            Price = 119.99m,
                            SKU = "MEN-JNS-001",
                            SalePrice = 79.99m,
                            StockQuantity = 30,
                            SubCategory = "Jeans"
                        },
                        new
                        {
                            Id = 3,
                            AvailableColors = "[\"White\",\"Black\",\"Grey\",\"Navy\"]",
                            AvailableSizes = "[\"XS\",\"S\",\"M\",\"L\",\"XL\",\"XXL\"]",
                            Category = "Men",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "T-Shirt",
                            Name = "Essential T-Shirt",
                            Price = 34.99m,
                            SKU = "MEN-TSH-001",
                            StockQuantity = 120,
                            SubCategory = "T-Shirts"
                        },
                        new
                        {
                            Id = 4,
                            AvailableColors = "[\"Black\",\"Brown\"]",
                            AvailableSizes = "[\"S\",\"M\",\"L\"]",
                            Category = "Men",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1627123424574-724758594e93?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Accessories",
                            Name = "Leather Belt",
                            Price = 45.00m,
                            SKU = "MEN-ACC-001",
                            StockQuantity = 100,
                            SubCategory = "Accessories"
                        },
                        new
                        {
                            Id = 5,
                            AvailableColors = "[\"Floral\",\"Pink\",\"White\"]",
                            AvailableSizes = "[\"XS\",\"S\",\"M\",\"L\"]",
                            Category = "Women",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Dress",
                            Name = "Floral Midi Dress",
                            Price = 149.99m,
                            SKU = "WOM-DRS-001",
                            SalePrice = 99.99m,
                            StockQuantity = 25,
                            SubCategory = "Dresses"
                        },
                        new
                        {
                            Id = 6,
                            AvailableColors = "[\"Beige\",\"White\",\"Black\"]",
                            AvailableSizes = "[\"S\",\"M\",\"L\",\"XL\"]",
                            Category = "Women",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1594938298603-c8148c4b4af1?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Pants",
                            Name = "Linen Trousers",
                            Price = 89.99m,
                            SKU = "WOM-PNT-001",
                            StockQuantity = 15,
                            SubCategory = "Pants"
                        },
                        new
                        {
                            Id = 7,
                            AvailableColors = "[\"Grey\",\"Beige\",\"Pink\"]",
                            AvailableSizes = "[\"S\",\"M\",\"L\"]",
                            Category = "Women",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Tops",
                            Name = "Knit Sweater",
                            Price = 109.99m,
                            SKU = "WOM-TOP-001",
                            SalePrice = 74.99m,
                            StockQuantity = 18,
                            SubCategory = "Tops"
                        },
                        new
                        {
                            Id = 8,
                            AvailableColors = "[\"Black\",\"Navy\",\"Emerald\"]",
                            AvailableSizes = "[\"S\",\"M\",\"L\"]",
                            Category = "Women",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Premium",
                            Name = "Silk Velvet Gown",
                            Price = 299.99m,
                            SKU = "WOM-PRM-001",
                            StockQuantity = 5,
                            SubCategory = "Premium Collection"
                        },
                        new
                        {
                            Id = 9,
                            AvailableColors = "[\"White\",\"Pink\",\"Blue\"]",
                            AvailableSizes = "[\"0-3M\",\"3-6M\",\"6-9M\"]",
                            Category = "Kids",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1522771930-78848d9293e8?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Onesie",
                            Name = "Baby Organic Onesie",
                            Price = 44.99m,
                            SKU = "KID-NWB-001",
                            SalePrice = 29.99m,
                            StockQuantity = 60,
                            SubCategory = "Newborn"
                        },
                        new
                        {
                            Id = 10,
                            AvailableColors = "[\"Pink\",\"White\",\"Gold\"]",
                            AvailableSizes = "[\"2Y\",\"4Y\",\"6Y\",\"8Y\"]",
                            Category = "Kids",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Dress",
                            Name = "Girls Tulle Dress",
                            Price = 59.99m,
                            SKU = "KID-GRL-001",
                            StockQuantity = 20,
                            SubCategory = "Girl"
                        },
                        new
                        {
                            Id = 11,
                            AvailableColors = "[\"Blue\",\"Grey\"]",
                            AvailableSizes = "[\"2Y\",\"4Y\",\"6Y\",\"8Y\"]",
                            Category = "Kids",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1544131580-0a187d97b102?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Pants",
                            Name = "Boys Denim Joggers",
                            Price = 49.99m,
                            SKU = "KID-BOY-001",
                            StockQuantity = 33,
                            SubCategory = "Boy"
                        },
                        new
                        {
                            Id = 12,
                            AvailableColors = "[\"Red\",\"Blue\",\"White\"]",
                            AvailableSizes = "[\"5\",\"6\",\"7\",\"8\"]",
                            Category = "Kids",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Shoes",
                            Name = "Toddler Canvas Shoes",
                            Price = 39.99m,
                            SKU = "KID-SHO-001",
                            StockQuantity = 40,
                            SubCategory = "Shoes"
                        },
                        new
                        {
                            Id = 13,
                            AvailableColors = "[\"White\",\"Black\",\"Green\"]",
                            AvailableSizes = "[\"S\",\"M\",\"L\"]",
                            Category = "Kids",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1622273501267-a220b1283397?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "T-Shirt",
                            Name = "Clearance Tee",
                            Price = 19.99m,
                            SKU = "KID-SAL-001",
                            SalePrice = 9.99m,
                            StockQuantity = 100,
                            SubCategory = "Boy"
                        },
                        new
                        {
                            Id = 14,
                            AvailableColors = "[\"Navy/White\",\"Grey/Black\"]",
                            AvailableSizes = "[\"S\",\"M\",\"L\",\"XL\"]",
                            Category = "Men",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Shirt",
                            Name = "Striped Polo Shirt",
                            Price = 55.00m,
                            SKU = "MEN-SHT-002",
                            StockQuantity = 40,
                            SubCategory = "Shirts"
                        },
                        new
                        {
                            Id = 15,
                            AvailableColors = "[\"Olive\",\"Khaki\",\"Black\"]",
                            AvailableSizes = "[\"30\",\"32\",\"34\",\"36\"]",
                            Category = "Men",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1617114919297-3c8ddb01f599?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Jeans",
                            Name = "Cargo Jeans",
                            Price = 89.99m,
                            SKU = "MEN-JNS-002",
                            StockQuantity = 25,
                            SubCategory = "Jeans"
                        },
                        new
                        {
                            Id = 16,
                            AvailableColors = "[\"White\",\"Navy\",\"Black\"]",
                            AvailableSizes = "[\"S\",\"M\",\"L\",\"XL\"]",
                            Category = "Men",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "T-Shirt",
                            Name = "Pocket T-Shirt",
                            Price = 24.99m,
                            SKU = "MEN-TSH-002",
                            StockQuantity = 80,
                            SubCategory = "T-Shirts"
                        },
                        new
                        {
                            Id = 17,
                            AvailableColors = "[\"Grey\",\"Black\",\"Navy\"]",
                            AvailableSizes = "[\"One Size\"]",
                            Category = "Men",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1576871333021-d10ca45a55cc?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Accessories",
                            Name = "Beanie Hat",
                            Price = 25.00m,
                            SKU = "MEN-ACC-002",
                            StockQuantity = 60,
                            SubCategory = "Accessories"
                        },
                        new
                        {
                            Id = 18,
                            AvailableColors = "[\"Black/White\",\"Navy/White\"]",
                            AvailableSizes = "[\"XS\",\"S\",\"M\",\"L\"]",
                            Category = "Women",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Dress",
                            Name = "Polka Dot Dress",
                            Price = 110.00m,
                            SKU = "WOM-DRS-002",
                            StockQuantity = 30,
                            SubCategory = "Dresses"
                        },
                        new
                        {
                            Id = 19,
                            AvailableColors = "[\"Beige\",\"Black\",\"Rust\"]",
                            AvailableSizes = "[\"S\",\"M\",\"L\"]",
                            Category = "Women",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1594938298603-c8148c4b4af1?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Pants",
                            Name = "Wide-Leg Culottes",
                            Price = 95.00m,
                            SKU = "WOM-PNT-002",
                            StockQuantity = 20,
                            SubCategory = "Pants"
                        },
                        new
                        {
                            Id = 20,
                            AvailableColors = "[\"White\",\"Pink\",\"Lavender\"]",
                            AvailableSizes = "[\"XS\",\"S\",\"M\",\"L\"]",
                            Category = "Women",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Tops",
                            Name = "Silk Blouse",
                            Price = 75.00m,
                            SKU = "WOM-TOP-002",
                            StockQuantity = 25,
                            SubCategory = "Tops"
                        },
                        new
                        {
                            Id = 21,
                            AvailableColors = "[\"Champagne\",\"Navy\",\"Silver\"]",
                            AvailableSizes = "[\"S\",\"M\",\"L\"]",
                            Category = "Women",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Premium",
                            Name = "Evening Lace Gown",
                            Price = 350.00m,
                            SKU = "WOM-PRM-002",
                            StockQuantity = 8,
                            SubCategory = "Premium Collection"
                        },
                        new
                        {
                            Id = 22,
                            AvailableColors = "[\"White\",\"Grey\",\"Beige\"]",
                            AvailableSizes = "[\"0-6M\",\"6-12M\"]",
                            Category = "Kids",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1522771930-78848d9293e8?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Accessories",
                            Name = "Knitted Baby Hat",
                            Price = 15.00m,
                            SKU = "KID-NWB-002",
                            StockQuantity = 50,
                            SubCategory = "Newborn"
                        },
                        new
                        {
                            Id = 23,
                            AvailableColors = "[\"Pink\",\"Silver\",\"Gold\"]",
                            AvailableSizes = "[\"2Y\",\"4Y\",\"6Y\",\"8Y\"]",
                            Category = "Kids",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1503911216082-ef120f269324?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Pants",
                            Name = "Glitter Leggings",
                            Price = 25.00m,
                            SKU = "KID-GRL-002",
                            StockQuantity = 40,
                            SubCategory = "Girl"
                        },
                        new
                        {
                            Id = 24,
                            AvailableColors = "[\"Black\",\"Grey\",\"Blue\"]",
                            AvailableSizes = "[\"2Y\",\"4Y\",\"6Y\",\"8Y\"]",
                            Category = "Kids",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1622273501267-a220b1283397?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "T-Shirt",
                            Name = "Graphic Logo Tee",
                            Price = 19.99m,
                            SKU = "KID-BOY-002",
                            StockQuantity = 60,
                            SubCategory = "Boy"
                        },
                        new
                        {
                            Id = 25,
                            AvailableColors = "[\"Yellow\",\"Blue\",\"Red\"]",
                            AvailableSizes = "[\"7\",\"8\",\"9\",\"10\"]",
                            Category = "Kids",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Shoes",
                            Name = "Rubber Rain Boots",
                            Price = 45.00m,
                            SKU = "KID-SHO-002",
                            StockQuantity = 30,
                            SubCategory = "Shoes"
                        },
                        new
                        {
                            Id = 26,
                            AvailableColors = "[\"Blue\",\"Multicolor\",\"Yellow\"]",
                            AvailableSizes = "[\"S\",\"M\",\"L\"]",
                            Category = "Kids",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1519689680058-324335c77eba?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Shorts",
                            Name = "Summer Sale Shorts",
                            Price = 29.99m,
                            SKU = "KID-SAL-002",
                            SalePrice = 14.99m,
                            StockQuantity = 80,
                            SubCategory = "Boy"
                        },
                        new
                        {
                            Id = 27,
                            AvailableColors = "[\"White\",\"Black\",\"Navy\",\"Olive\"]",
                            AvailableSizes = "[\"S\",\"M\",\"L\",\"XL\"]",
                            Category = "Men",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "T-Shirt",
                            Name = "Classic Crew Tee",
                            Price = 29.99m,
                            SKU = "MEN-TSH-003",
                            StockQuantity = 100,
                            SubCategory = "T-Shirts"
                        },
                        new
                        {
                            Id = 28,
                            AvailableColors = "[\"Blue\",\"Light Wash\"]",
                            AvailableSizes = "[\"S\",\"M\",\"L\",\"XL\"]",
                            Category = "Men",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Shirt",
                            Name = "Chambray Shirt",
                            Price = 65.00m,
                            SKU = "MEN-SHT-003",
                            StockQuantity = 45,
                            SubCategory = "Shirts"
                        },
                        new
                        {
                            Id = 29,
                            AvailableColors = "[\"Black\"]",
                            AvailableSizes = "[\"30\",\"32\",\"34\",\"36\"]",
                            Category = "Men",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Jeans",
                            Name = "Black Skinny Jeans",
                            Price = 99.99m,
                            SKU = "MEN-JNS-003",
                            StockQuantity = 35,
                            SubCategory = "Jeans"
                        },
                        new
                        {
                            Id = 30,
                            AvailableColors = "[\"Brown\",\"Black\",\"Tan\"]",
                            AvailableSizes = "[\"One Size\"]",
                            Category = "Men",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1627123424574-724758594e93?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Accessories",
                            Name = "Leather Keyring",
                            Price = 15.00m,
                            SKU = "MEN-ACC-003",
                            StockQuantity = 200,
                            SubCategory = "Accessories"
                        },
                        new
                        {
                            Id = 31,
                            AvailableColors = "[\"Emerald\",\"Navy\",\"Silver\"]",
                            AvailableSizes = "[\"XS\",\"S\",\"M\",\"L\"]",
                            Category = "Women",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Dress",
                            Name = "Evening Slip Dress",
                            Price = 130.00m,
                            SKU = "WOM-DRS-003",
                            StockQuantity = 25,
                            SubCategory = "Dresses"
                        },
                        new
                        {
                            Id = 32,
                            AvailableColors = "[\"White/Navy\",\"Grey/White\"]",
                            AvailableSizes = "[\"S\",\"M\",\"L\"]",
                            Category = "Women",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Tops",
                            Name = "Striped Knit Top",
                            Price = 45.00m,
                            SKU = "WOM-TOP-003",
                            StockQuantity = 40,
                            SubCategory = "Tops"
                        },
                        new
                        {
                            Id = 33,
                            AvailableColors = "[\"Black\",\"Navy\",\"Khaki\"]",
                            AvailableSizes = "[\"S\",\"M\",\"L\",\"XL\"]",
                            Category = "Women",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1594938298603-c8148c4b4af1?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Pants",
                            Name = "High-Waist Pants",
                            Price = 90.00m,
                            SKU = "WOM-PNT-003",
                            StockQuantity = 15,
                            SubCategory = "Pants"
                        },
                        new
                        {
                            Id = 34,
                            AvailableColors = "[\"Beige\",\"Camel\",\"Light Grey\"]",
                            AvailableSizes = "[\"S\",\"M\",\"L\"]",
                            Category = "Women",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Premium",
                            Name = "Cashmere Cardigan",
                            Price = 220.00m,
                            SKU = "WOM-PRM-003",
                            StockQuantity = 10,
                            SubCategory = "Premium Collection"
                        },
                        new
                        {
                            Id = 35,
                            AvailableColors = "[\"White\",\"Pastel\",\"Mint\"]",
                            AvailableSizes = "[\"One Size\"]",
                            Category = "Kids",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1522771930-78848d9293e8?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Accessories",
                            Name = "Newborn Swaddle Set",
                            Price = 35.00m,
                            SKU = "KID-NWB-003",
                            StockQuantity = 50,
                            SubCategory = "Newborn"
                        },
                        new
                        {
                            Id = 36,
                            AvailableColors = "[\"Blue\",\"White\"]",
                            AvailableSizes = "[\"4Y\",\"6Y\",\"8Y\",\"10Y\"]",
                            Category = "Kids",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1503911216082-ef120f269324?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Pants",
                            Name = "Denim Skirt",
                            Price = 30.00m,
                            SKU = "KID-GRL-003",
                            StockQuantity = 35,
                            SubCategory = "Girl"
                        },
                        new
                        {
                            Id = 37,
                            AvailableColors = "[\"Grey\",\"Navy\",\"Black\"]",
                            AvailableSizes = "[\"4Y\",\"6Y\",\"8Y\",\"10Y\"]",
                            Category = "Kids",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1622273501267-a220b1283397?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Tops",
                            Name = "Graphic Hoodie",
                            Price = 39.99m,
                            SKU = "KID-BOY-003",
                            StockQuantity = 45,
                            SubCategory = "Boy"
                        },
                        new
                        {
                            Id = 38,
                            AvailableColors = "[\"Black\",\"Blue\",\"Neon\"]",
                            AvailableSizes = "[\"1\",\"2\",\"3\",\"4\"]",
                            Category = "Kids",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Shoes",
                            Name = "Running Shoes",
                            Price = 55.00m,
                            SKU = "KID-SHO-003",
                            StockQuantity = 25,
                            SubCategory = "Shoes"
                        },
                        new
                        {
                            Id = 39,
                            AvailableColors = "[\"Red\",\"Navy\",\"Green\"]",
                            AvailableSizes = "[\"4Y\",\"6Y\",\"8Y\"]",
                            Category = "Kids",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1544131580-0a187d97b102?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Outerwear",
                            Name = "Winter Sale Coat",
                            Price = 80.00m,
                            SKU = "KID-SAL-003",
                            SalePrice = 40.00m,
                            StockQuantity = 15,
                            SubCategory = "Girl"
                        },
                        new
                        {
                            Id = 40,
                            AvailableColors = "[\"Black\",\"Grey\"]",
                            AvailableSizes = "[\"S\",\"M\",\"L\",\"XL\"]",
                            Category = "Men",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "T-Shirt",
                            Name = "Graphic Band Tee",
                            Price = 35.00m,
                            SKU = "MEN-TSH-004",
                            StockQuantity = 60,
                            SubCategory = "T-Shirts"
                        },
                        new
                        {
                            Id = 41,
                            AvailableColors = "[\"Red/Black\",\"Blue/Grey\"]",
                            AvailableSizes = "[\"S\",\"M\",\"L\",\"XL\"]",
                            Category = "Men",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1591047139829-d91aec369bb7?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Shirt",
                            Name = "Flannel Shirt",
                            Price = 59.99m,
                            SKU = "MEN-SHT-004",
                            StockQuantity = 40,
                            SubCategory = "Shirts"
                        },
                        new
                        {
                            Id = 42,
                            AvailableColors = "[\"Indigo\",\"Black\"]",
                            AvailableSizes = "[\"30\",\"32\",\"34\",\"36\"]",
                            Category = "Men",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1542272604-787c3835535d?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Jeans",
                            Name = "Relaxed Fit Jeans",
                            Price = 85.00m,
                            SKU = "MEN-JNS-004",
                            StockQuantity = 50,
                            SubCategory = "Jeans"
                        },
                        new
                        {
                            Id = 43,
                            AvailableColors = "[\"Black\",\"Tortoise\"]",
                            AvailableSizes = "[\"One Size\"]",
                            Category = "Men",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1511499767350-a151528523f8ae?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Accessories",
                            Name = "Sunglasses",
                            Price = 120.00m,
                            SKU = "MEN-ACC-004",
                            StockQuantity = 30,
                            SubCategory = "Accessories"
                        },
                        new
                        {
                            Id = 44,
                            AvailableColors = "[\"Red\",\"Blue\",\"Black\"]",
                            AvailableSizes = "[\"S\",\"M\",\"L\"]",
                            Category = "Women",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Dress",
                            Name = "Wrap Maxi Dress",
                            Price = 160.00m,
                            SKU = "WOM-DRS-004",
                            StockQuantity = 20,
                            SubCategory = "Dresses"
                        },
                        new
                        {
                            Id = 45,
                            AvailableColors = "[\"White\",\"Pink\",\"Floral\"]",
                            AvailableSizes = "[\"XS\",\"S\",\"M\",\"L\"]",
                            Category = "Women",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Tops",
                            Name = "Off-Shoulder Top",
                            Price = 50.00m,
                            SKU = "WOM-TOP-004",
                            StockQuantity = 35,
                            SubCategory = "Tops"
                        },
                        new
                        {
                            Id = 46,
                            AvailableColors = "[\"Pink\",\"Black\",\"White\"]",
                            AvailableSizes = "[\"S\",\"M\",\"L\"]",
                            Category = "Women",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Pants",
                            Name = "Pleated Skirt",
                            Price = 80.00m,
                            SKU = "WOM-PNT-004",
                            StockQuantity = 25,
                            SubCategory = "Pants"
                        },
                        new
                        {
                            Id = 47,
                            AvailableColors = "[\"Camel\",\"Black\",\"Grey\"]",
                            AvailableSizes = "[\"S\",\"M\",\"L\"]",
                            Category = "Women",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1591047139829-d91aec369bb7?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Premium",
                            Name = "Wool Overcoat",
                            Price = 300.00m,
                            SKU = "WOM-PRM-004",
                            StockQuantity = 5,
                            SubCategory = "Premium Collection"
                        },
                        new
                        {
                            Id = 48,
                            AvailableColors = "[\"White\",\"Pink\",\"Blue\"]",
                            AvailableSizes = "[\"0-3M\",\"3-6M\"]",
                            Category = "Kids",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1522771930-78848d9293e8?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Shoes",
                            Name = "Baby Booties",
                            Price = 20.00m,
                            SKU = "KID-NWB-004",
                            StockQuantity = 40,
                            SubCategory = "Newborn"
                        },
                        new
                        {
                            Id = 49,
                            AvailableColors = "[\"Floral\",\"White\",\"Yellow\"]",
                            AvailableSizes = "[\"2Y\",\"4Y\",\"6Y\"]",
                            Category = "Kids",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Dress",
                            Name = "Summer Sundress",
                            Price = 35.00m,
                            SKU = "KID-GRL-004",
                            StockQuantity = 25,
                            SubCategory = "Girl"
                        },
                        new
                        {
                            Id = 50,
                            AvailableColors = "[\"Yellow\",\"Blue\"]",
                            AvailableSizes = "[\"4Y\",\"6Y\",\"8Y\"]",
                            Category = "Kids",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1544131580-0a187d97b102?w=600\\u0026auto=format\\u0026fit=crop\"]",
                            ItemType = "Outerwear",
                            Name = "Raincoat",
                            Price = 45.00m,
                            SKU = "KID-BOY-004",
                            StockQuantity = 15,
                            SubCategory = "Boy"
                        });
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultZip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend.Models.Order", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.OrderItem", b =>
                {
                    b.HasOne("Backend.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
